CREATE TABLE IF NOT EXISTS analisis (
  id INT AUTO_INCREMENT PRIMARY KEY,
  motivo_anulacion VARCHAR(255) NOT NULL,
  importe DECIMAL(10,2) DEFAULT 0,
  cant_analisis INT DEFAULT 0,
  fecha_analisis DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
