CREATE TABLE transportistas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(150) NOT NULL,
  apellidos VARCHAR(150) NOT NULL,
  codigo_identificador VARCHAR(50) NOT NULL UNIQUE,
  placa VARCHAR(20) DEFAULT NULL,
  ruta VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
